### ISSUE TITLE
Work with modern typographist/core?

### ISSUE THREAD

**Issue by FaraFara** [typographist/postcss#88]
Is there a patch planned to work with modern version typographist/core?

**Comment by mg901** [comment]
@FaraFara yep

**Comment by FaraFara** [comment]
OK,

May you patch dependinces in package.json for modern version @core and postcss?

**Comment by mg901** [comment]
@FaraFara not at the moment. If you need a stable version, use [typographist](https://www.npmjs.com/package/typographist)

**Comment by mg901** [comment]
@FaraFara, typographist/postcss now has updated core.
